name: 'Tracer Action'
description: Tracer description
author: FastCI Tracer
inputs:
  jfrog_user_writer:
    description: "JFrog User Writer"
    required: false
    
  jfrog_password_writer:
    description: "JFrog Password Writer"
    required: false
    

  fastci_otel_endpoint:
    description: "OpenTelemetry Endpoint that will receive the traces. If 'file://<path>', the OTel will be written to the file path"
    required: false
    default: "ingress.coralogix.us:443"

  github_token:
    description: The repository token with Workflow permissions. i.e. secrets.GITHUB_TOKEN
    required: true

  fastci_otel_token:
    description: "OpenTelemetry token"
    required: true

  version:
    description: "Version of the bashi binary to use. If 'local', the binary will be used from the path of /tmp/fastci/tools/bashi-{ARCH}}"
    required: false
    default: "v0.15.3"

  job_name_for_tests_only:
    description: "Override job name for tests only (used in CI tests)"
    required: false
    default: ""

  extra_attributes:
    description: "Extra attributes to add to the trace"
    required: false
    default: "cx.subsystem.name=${{github.repository}},cx.application.name=${{github.repository_owner}},cicd.pipeline.name=${{github.workflow}},cicd.pipeline.run_id=${{github.run_id}},cicd.pipeline.repository=${{github.repository}},cicd.pipeline.repository_owner=${{github.repository_owner}}"
  
  full_repo_name:
    description: "Full repository name"
    required: false
    default: "jfrog-fastci/fastci"

  fail_on_error:
    description: 'Fail the CI if an error is detected'
    required: false
    default: false

  setup_timeout_seconds:
    description: 'Timeout for the setup phase in seconds'
    required: false
    default: '30'
  
  store_cache_timeout_seconds:
    description: 'Timeout for storing cache in seconds'
    required: false
    default: '60'
  
  export_otel_timeout_seconds:
    description: 'Timeout for exporting OpenTelemetry data in seconds'
    required: false
    default: '15'
  
  install_bashi:
    description: 'Install bashi'
    required: false
    default: true
  
  bashi_log_level:
    description: 'Bashi log level (trace, debug, info, warn, error, fatal, panic)'
    required: false
    default: 'debug'


runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js' 