name: 'Tracer Action'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Fastci Tracer Action
      run: |
        curl -O -L https://raw.githubusercontent.com/fastci-dev/tracer-bin/main/tracer
        chmod +x tracer
        sudo ./tracer &
        sleep 5
