name: Tracer Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Fastci tracer
      run: |
        curl -O -L https://raw.githubusercontent.com/fastci-dev/tracer-bin/main/tracer
        chmod +x tracer
        sudo ./tracer &
